### ISSUE TITLE
[oe4t-patches-l4t-r35.1] compilation error when CONFIG_ARCH_TEGRA_19x_SOC=y (Jetson AGX Xavier) OR CONFIG_ARCH_TEGRA_18x_SOC=y

### ISSUE THREAD

**Issue by creich** [OE4T/linux-tegra-5.10#5]
Hi there,

i am working on a yocto based build for an Nvidia Jetson AGX Xavier board. When switching to this branch, the default config (which activated `CONFIG_ARCH_TEGRA_23x_SOC`) it builds as expected.
But when i change the kernel config to activate `CONFIG_ARCH_TEGRA_19x_SOC=y` the build fails.
Similar problem with `CONFIG_ARCH_TEGRA_18x_SOC=y`

As far as i can tell from a first glimpse into the code, there are some changes to the `tegra_pinctrl_soc_data` in `drivers/pinctrl/tegra/pinctrl-tegra.h`. 
For example there are some values removed from the struct:
> | .build/tmp/work-shared/jetson-agx-xavier-devkit/kernel-source/nvidia/drivers/pinctrl/pinctrl-tegra194.c:928:10: error: 'const struct tegra_pinctrl_soc_data' has no member named 'is_gpio_reg_support'
> |   928 |         .is_gpio_reg_support = true,
> |       |          ^~~~~~~~~~~~~~~~~~~
> | ./build/tmp/work-shared/jetson-agx-xavier-devkit/kernel-source/nvidia/drivers/pinctrl/pinctrl-tegra194.c:929:10: error: 'const struct tegra_pinctrl_soc_data' has no member named 'input_tristate_enable'
> |   929 |         .input_tristate_enable = true,
> |       |          ^~~~~~~~~~~~~~~~~~~~~
> | ./build/tmp/work-shared/jetson-agx-xavier-devkit/kernel-source/nvidia/drivers/pinctrl/pinctrl-tegra194.c:930:10: error: 'const struct tegra_pinctrl_soc_data' has no member named 'output_input_disable'
> |   930 |         .output_input_disable = true,

there are more issues, but i don't think it really helps to paste them here.
My best guess is that either i have made a major mistake in the config OR the latest kernel version was never tested/build for the 'older' SOCs.

I'd be happy to help with more details or even work on a patch. But i'd need at least some guidance on how to proceed, since there are some major changes to the initialization of the GPIOs.

kind regards
Christian

**Comment by madisongh** [comment]
I've run into this before with the 4.9 and 4.4 kernels.  NVIDIA doesn't appear to do any testing of config dependencies in their downstream kernels, particularly in their semi-out-of-tree drivers, so it's really not practical to go too far with trimming down the kernel configs. You can run into build errors like what you're seeing here, or worse, strange runtime errors/crashes that are difficult to debug. Even if you can come up with a working slimmed-down configuration in this release, you could end up having to completely re-do your changes on some future release due to some other dependency that might creep in.

I'd recommend just sticking with the configuration in [tegra_defconfig](https://github.com/OE4T/linux-tegra-5.10/blob/oe4t-patches-l4t-r35.1/arch/arm64/configs/tegra_defconfig) as a base and being very selective about any removals.  I used to try and fix these sorts of issues myself, and it just got to be too much of a maintenance burden - more than the benefit I was getting out of having a smaller kernel.

If you're seeing a significant size reduction or other improvement with making the configs more granular, you could try opening a discussion on the NVIDIA dev forum to see if they're open to taking such changes.

**Comment by creich** [comment]
thanks for the feedback. I'll keep that in mind for future changes to my config :)

unfortunately the problem persists even if i do NOT remove any settings.
Since i would like to switch up to 5.10 i actually need to be able to at least **additionally activate** `CONFIG_ARCH_TEGRA_19x_SOC`.

but if i get you right, it might be necessary to bring that up in the NVIDIA dev forums. Is that correct?

**Comment by madisongh** [comment]
> Since i would like to switch up to 5.10 i actually need to be able to at least additionally activate CONFIG_ARCH_TEGRA_19x_SOC.

The stock kernel config works for both T194 and T234 devices, so you shouldn't have to set it.  If there's something that that kernel config enables that you think you need, then yes, asking on the dev forum might be a good idea.

**Comment by creich** [comment]
should work, or is really meant to be used for it?
i know that it boots at least. but is it supposed to be used like that? if so, why did NVIDIA keep the older SoC options in the kernel config?

**Comment by madisongh** [comment]
> should work, or is really meant to be used for it?

Meant to be used.  The subtrees under `nvidia` are their semi-out-of-tree drivers and device trees (they maintain them in separate git repos on their git server), which appear to get shared across multiple kernel versions. The old stuff may still be there because of that.  Or maybe they just haven't gotten round to cleaning them up properly.

**Comment by ichergui** [comment]
Hey guys @madisongh @creich 
Are we still consider this issue or we should close it ?

**Comment by creich** [comment]
I'd say we can close it.
It seems to work as expected.

Thanks for bringing that up again.

**Comment by ichergui** [comment]
Thanks @creich
